'use client';

import { useState } from 'react';
import type { Alert } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ArrowUpDown } from 'lucide-react';

const mockAlerts: Alert[] = [
  { id: 'SH-101', timestamp: '2023-10-27 14:40:00', severity: 'High', description: 'Anomalous API usage pattern detected for user_123', ttp_id: 'T1497.003', status: 'New', source: 'Shield', entity: 'API Gateway' },
  { id: 'SH-102', timestamp: '2023-10-27 14:35:10', severity: 'Critical', description: 'PII leakage detected in API response to IP 192.168.1.100', ttp_id: 'T1530', status: 'New', source: 'Shield', entity: 'Patient Records API' },
  { id: 'SH-103', timestamp: '2023-10-27 13:50:25', severity: 'Medium', description: 'Excessive 4xx errors from client IP 203.0.113.45', ttp_id: 'T1110', status: 'In Progress', source: 'Shield', entity: 'API Gateway' },
  { id: 'SH-104', timestamp: '2023-10-26 21:30:00', severity: 'High', description: 'Potential API scraping activity from a single user session', ttp_id: 'T1003', status: 'Resolved', source: 'Shield', entity: 'Appointments API' },
];

const severityVariant: Record<Alert['severity'], 'destructive' | 'secondary' | 'default'> = {
  Critical: 'destructive',
  High: 'secondary',
  Medium: 'default',
  Low: 'default',
};

export function ShieldAlertsTable() {
  const [alerts] = useState<Alert[]>(mockAlerts);
  const [sortConfig, setSortConfig] = useState<{ key: keyof Alert; direction: 'ascending' | 'descending' } | null>({ key: 'timestamp', direction: 'descending' });

  const sortedAlerts = [...alerts].sort((a, b) => {
    if (sortConfig) {
      if (a[sortConfig.key] < b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? -1 : 1;
      }
      if (a[sortConfig.key] > b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? 1 : -1;
      }
    }
    return 0;
  });

  const requestSort = (key: keyof Alert) => {
    let direction: 'ascending' | 'descending' = 'ascending';
    if (sortConfig && sortConfig.key === key && sortConfig.direction === 'ascending') {
      direction = 'descending';
    }
    setSortConfig({ key, direction });
  };

  return (
    <Card className="rounded-2xl shadow-lg">
      <CardHeader>
        <CardTitle>Recent Shield Alerts</CardTitle>
        <CardDescription>Security alerts generated by Health API Shield.</CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>
                 <Button variant="ghost" onClick={() => requestSort('severity')}>
                    Severity <ArrowUpDown className="ml-2 h-4 w-4" />
                  </Button>
              </TableHead>
              <TableHead>Description</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>
                 <Button variant="ghost" onClick={() => requestSort('timestamp')}>
                    Timestamp <ArrowUpDown className="ml-2 h-4 w-4" />
                  </Button>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {sortedAlerts.map((alert) => (
              <TableRow key={alert.id}>
                <TableCell>
                  <Badge variant={severityVariant[alert.severity]}>{alert.severity}</Badge>
                </TableCell>
                <TableCell className="font-medium">{alert.description}</TableCell>
                <TableCell>
                  <Badge variant="outline">{alert.status}</Badge>
                </TableCell>
                <TableCell>{new Date(alert.timestamp).toLocaleString()}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
